language: node_js
sudo: required
# 指定node_js版本
node_js: 
  - lts/*
cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install
  - git clone --depth=1 https://github.com/theme-next/theme-next-han themes/next/source/lib/Han
  - git clone --depth=1 https://github.com/theme-next/theme-next-quicklink.git themes/next/source/lib/quicklink
  - git clone --depth=1 https://github.com/theme-next/theme-next-pangu.git themes/next/source/lib/pangu
  - git clone --depth=1 https://github.com/theme-next/theme-next-reading-progress themes/next/source/lib/reading_progress
  - git clone --depth=1 https://github.com/edsion1107/theme-next-live2d.git themes/next/source/lib/live2d

script:
  - hexo clean
  - hexo generate

# GitHub Pages Deployment
deploy:
  provider: pages
  skip-cleanup: true  # 必须跳过清理，否则过程中生成的文件（要发布的静态资源）会被清理
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false   # 设置为 false 时，使用 `git push --force` 命令覆盖历史记录
  on:
    branch: master    # 仅监听 master 分支
  target-branch: gh-pages   # 用于存放静态资源的分支
  local-dir: public   # `hexo g` 命令生成的静态资源所在路径
  fqdn: blog.i1hao.com    # 自定义域名